language: node_js
dist: trusty
sudo: required
node_js: 5
install:
  - npm install bower -g
  - npm install
  - bower install
script:
  - node ./test-server.js &
  - sleep 2 && pulp test
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
